name: Deploy
on:
  push:
    branches: [master]

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
          - name: executing remote ssh commands using password
            uses: appleboy/ssh-action@v0.1.10
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USER }}
              password: ${{ secrets.PASSWORD }}
              port: ${{ secrets.PORT }}
              script: |
                cd /home/${{ secrets.USER }}/ToDo-list
                git pull && npm ci && npm run build && docker compose up -d && npx prisma migrate deploy && pm2 start ecosystem.config.js
     